# Generated by Django 5.0.6 on 2024-05-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0002_alter_class_lecturer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='number',
            new_name='semester',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='name',
            field=models.CharField(default='CLASS', max_length=50),
            preserve_default=False,
        ),
    ]
