# Generated by Django 5.0.6 on 2024-05-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0003_rename_number_semester_semester_lecturer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='name',
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default='class', max_length=50),
            preserve_default=False,
        ),
    ]
