# Generated by Django 5.0.6 on 2024-05-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0004_remove_lecturer_name_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrolment',
            name='grade',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
