# Generated by Django 5.0.6 on 2024-05-19 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0005_alter_studentenrolment_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='lecturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gradebook.lecturer'),
        ),
        migrations.AlterField(
            model_name='studentenrolment',
            name='grade_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
